### ISSUE TITLE
Cannot call method 'on' of undefined

### ISSUE THREAD

**Issue by kakashif** [GannettDigital/busterbunny.js#4]
Once a connection is lost, we get "Cannot call method 'on' of undefined" exception and the application has to be restarted in order to reconnect to RabbitMq.

**Comment by enigmatic00** [comment]
I believe this issue is fixed with the release of 0.4.1

**Comment by kakashif** [comment]
There were some doubts but if 0.4.1 fixes it, then this issue will be closed.

**Comment by enigmatic00** [comment]
Gotcha, thanks

**Comment by binaryalchemist** [comment]
@kakashif  has this been resolved?  I would like to close this issue.

**Comment by kakashif** [comment]
I have not come across the error again.  Therefore I will close this issue.
